export { default as Header } from './Header/Header'
export { default as Footer } from './Footer/Footer'
export { default as Partners } from './Partners/Partners'
export { default as Questions } from './Questions/Questions'
export { default as Services } from './Services/Services'
export { default as Objects } from './Objects/Objects'
export { default as CallToAction } from './CallToAction/CallToAction'
export { default as MainPicture } from './MainPicture/MainPicture'
